# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: "%env(APP_SECRET)%"
  csrf_protection: true # Protection à la faille CSRF
  http_method_override: false
  handle_all_throwables: true

  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    handler_id: session.handler.native_file # Pour travailler avec les sessions (users connectés)
    cookie_lifetime: 604800 # Durée du cookie (session)
    gc_maxlifetime: 604800 # Garbage Collector, sécurise le cookie encore plus
    sid_bits_per_character: 5 # Encodage de la session par un certain nombre de bits par caractère => DÉFINIT LE REGEX
    cookie_secure: true # Sécurisation du cookie
    cookie_samesite: lax
    storage_factory_id: session.storage.factory.native

  #esi: true
  #fragments: true
  php_errors:
    log: true

when@test:
  framework:
    test: true
    session:
      storage_factory_id: session.storage.factory.mock_file
