twig:
  default_path: "%kernel.project_dir%/templates"
  form_themes: ["base_theme.html.twig"]
  paths: # Mise en place des directions vers le dossier emails & son CSS et templates
    "%kernel.project_dir%/emails/css": email_css
    "%kernel.project_dir%/emails/templates": email_templates

when@test:
  twig:
    strict_variables: true
